### ISSUE TITLE
The "fake data" button does not trigger the progress bars

### ISSUE THREAD

**Issue by neontomo** [neontomo/seo-for-devs#1]
# Pressing the "test with fake data" button should trigger a progress bar (easy fix)

## Contributing

Are you a beginner looking to contribute to a Github project? This is a great place to start! This project is beginner-friendly and a great way to get started with contributing to open source projects on Github.

### How to contribute

- Fork the repository
- Clone the repository
- Create a branch
- Make necessary changes and commit those changes
- Push changes to GitHub
- Submit your changes for review by creating a pull request
- That's it!

Check out [this guide](https://github.com/firstcontributions/first-contributions) for more information on how to contribute to Github projects.

## Screenshot

<img width="690" alt="image" src="https://github.com/neontomo/seo-4-devs/assets/105588693/ba0baf9b-bb57-4e2e-ad5d-bba9b1f8d3d3">

## The issue

When you press the "test with fake data" button, it should trigger the progress bars so that it looks like this:

<img width="602" alt="image" src="https://github.com/neontomo/seo-4-devs/assets/105588693/76977ed2-b4d5-45bc-94af-682040f1f09a">

## Fields affected:

- "Your website title"
- "Site keywords"
- "Your website description"

## Steps to take to implement a fix

- Add a function that triggers the progress bars when the "test with fake data" button is pressed.
- The function should be called `triggerProgressBars()`
- The function should be called ONLY when the "test with fake data" button is pressed

**Comment by Shubh8899** [comment]
Hey @neontomo I would like to work on this issue please, would you assign it to me.

**Comment by neontomo** [comment]
> Hey @neontomo I would like to work on this issue please, would you assign it to me.

Sure, done.
